spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spt?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8000